/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

void *
calcul_null_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

reponse *
calcul_addition_1_svc(data *argp, struct svc_req *rqstp)
{
  static reponse result;
  printf("appel de calcul_addition_1_svc(%d,%d)\n",argp->arg1,argp->arg2);
  result.errno = 0; /* Pas d'erreur */
  /* On additionne */
  result.somme = argp->arg1 + argp->arg2; 
  /* Overflow ? */
  int max = argp->arg1 > argp->arg2 ? argp->arg1 : argp->arg2;
  result.errno = ( result.somme < max ) ? 1 : 0; 
  return &result;
}
